# Generated by Django 6.1.1 on 2026-09-27 23:34

import accounts.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Resume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=accounts.models.user_resume_upload_path)),
                ('file_name', models.CharField(help_text='Original uploaded filename', max_length=255)),
                ('file_size', models.PositiveIntegerField(help_text='File size in bytes')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True, help_text='Designates this resume as the active resume for interview calibration')),
                ('extracted_education', models.JSONField(blank=True, default=list)),
                ('extracted_skills', models.JSONField(blank=True, default=list)),
                ('extracted_projects', models.JSONField(blank=True, default=list)),
                ('extracted_experience', models.JSONField(blank=True, default=list)),
                ('extracted_certifications', models.JSONField(blank=True, default=list)),
                ('analysis_summary', models.TextField(blank=True, default='')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resumes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-uploaded_at'],
                'indexes': [models.Index(fields=['user', '-uploaded_at'], name='accounts_re_user_id_deee2c_idx'), models.Index(fields=['user', 'is_active'], name='accounts_re_user_id_741a5d_idx')],
            },
        ),
    ]
