# Generated by Django 6.1.1 on 2026-09-30 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_resume'),
    ]

    operations = [
        migrations.AddField(
            model_name='resume',
            name='extracted_text',
            field=models.TextField(blank=True, default='', help_text='Raw full text extracted from the PDF resume'),
        ),
        migrations.AddField(
            model_name='resume',
            name='pdf_data',
            field=models.BinaryField(blank=True, help_text='Raw PDF binary file data stored directly in PostgreSQL', null=True),
        ),
    ]
