# Generated by Django 6.1.1 on 2026-10-05 16:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0003_resume_extracted_text_resume_pdf_data'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InterviewSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='AI Technical Mock Interview', max_length=255)),
                ('role', models.CharField(default='Full-Stack Engineer', max_length=100)),
                ('target_company', models.CharField(default='FAANG / Tier-1 Tech', max_length=100)),
                ('difficulty', models.CharField(choices=[('easy', 'Junior / Entry Level'), ('medium', 'Mid-Level Specialist'), ('hard', 'Senior / Lead'), ('expert', 'Staff / Principal Architect')], default='medium', max_length=50)),
                ('mode', models.CharField(choices=[('voice_and_text', 'Voice & Text Hybrid'), ('text_only', 'Text Only'), ('voice_first', 'Voice First')], default='voice_and_text', max_length=50)),
                ('status', models.CharField(choices=[('not_started', 'Not Started'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('abandoned', 'Abandoned')], default='in_progress', max_length=50)),
                ('total_questions', models.PositiveIntegerField(default=5)),
                ('current_question_index', models.PositiveIntegerField(default=0)),
                ('overall_score', models.FloatField(default=0.0)),
                ('technical_score', models.FloatField(default=0.0)),
                ('communication_score', models.FloatField(default=0.0)),
                ('depth_score', models.FloatField(default=0.0)),
                ('structure_score', models.FloatField(default=0.0)),
                ('readiness_index', models.IntegerField(default=0)),
                ('hiring_verdict', models.CharField(default='Pending Evaluation', help_text='Strong Hire, Lean Hire, Inconclusive, Needs Improvement', max_length=100)),
                ('overall_feedback', models.TextField(blank=True, default='')),
                ('key_strengths', models.JSONField(blank=True, default=list)),
                ('improvement_areas', models.JSONField(blank=True, default=list)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('duration_seconds', models.PositiveIntegerField(default=0)),
                ('resume', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='interview_sessions', to='accounts.resume')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interview_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='InterviewQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=1)),
                ('category', models.CharField(default='System Architecture & Engineering', help_text='System Design, Data Structures & Logic, Behavioral STAR, Resume Deep-Dive, Framework Internals', max_length=100)),
                ('question_text', models.TextField()),
                ('context_hint', models.TextField(blank=True, default='')),
                ('key_criteria', models.JSONField(blank=True, default=list)),
                ('candidate_answer', models.TextField(blank=True, default='')),
                ('is_answered', models.BooleanField(default=False)),
                ('answered_at', models.DateTimeField(blank=True, null=True)),
                ('time_taken_seconds', models.PositiveIntegerField(default=0)),
                ('score', models.FloatField(default=0.0)),
                ('accuracy_score', models.FloatField(default=0.0)),
                ('clarity_score', models.FloatField(default=0.0)),
                ('depth_score', models.FloatField(default=0.0)),
                ('rubric_feedback', models.TextField(blank=True, default='')),
                ('strengths', models.JSONField(blank=True, default=list)),
                ('gaps', models.JSONField(blank=True, default=list)),
                ('model_answer', models.TextField(blank=True, default='')),
                ('follow_up_drill', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='interviews.interviewsession')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.AddIndex(
            model_name='interviewsession',
            index=models.Index(fields=['user', '-started_at'], name='interviews__user_id_45f693_idx'),
        ),
        migrations.AddIndex(
            model_name='interviewsession',
            index=models.Index(fields=['user', 'status'], name='interviews__user_id_972c69_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='interviewquestion',
            unique_together={('session', 'order')},
        ),
    ]
